### ISSUE TITLE
The file bye is written wrong

### ISSUE THREAD

**Issue by LightYagami28** [Aledev3/Userbot-personal#2]

**Comment by LightYagami28** [comment]
from telethon import eventi


@userbot_personal.on(events.NewMessage(outgoing=True, pattern=r"\.bye"))

The correction are 

from telethon import events


@userbot_personal.on(events.NewMessage(outgoing=True, pattern=r"\.bye"))

**Comment by Falcone8** [comment]
@Falcone8 @Muffa0

**Comment by Exekutori** [comment]
resolved.
